name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
         
      - name: Setup Playwright 
      - uses: microsoft/playwright-github-action@v1
    
      - name: Install Dependencies
        run: dotnet restore
        
      - name: Install Playwright Dependencies
        run: npx playwright install 
                        
      - name: Build
        run: dotnet build --configuration Release --no-restore
                
      - name: Run SpecFlow Tests
        uses: cryptic-wizard/run-specflow-tests@v1.2.0        
        with:
           test-assembly-dll: PlaywrightDemo.Tests.UI/bin/Release/net6.0/PlaywrightDemo.Tests.UI.dll
           test-execution-json: PlaywrightDemo.Tests.UI/bin/Release/net6.0/PlaywrightDemo.Tests.UI.runtimeconfig.json
           framework: net6.0
           output-html: MyTestResults.html
